language: perl
before_script:
  - "git config --global user.email 'you@example.com'"
  - "git config --global user.name 'Your Name'"
perl:
  - 5.16
  - 5.14
before_install:
  cpanm -n Devel::Cover::Report::Coveralls
script:
  perl Build.PL && ./Build build && cover -test
after_success:
  cover -report coveralls
