name = "Minya"
author = "Tokuhiro Matsuno"
copyright_holder = "Tokuhiro Matsuno"
version = "0.0.1"
license = "Perl_5"
script_files = ['bin/minya']

plugins = [
    "Test::Pod",
    "Test::CPANMeta",
    "Test::Kwalitee",
    "Test::MinimumVersion"
]
